#!/usr/bin/python
#DESC: produce csv output of Klout topics for a single account
#DESC: batch this up for a bunch of accounts, visualize results with Gephi.
import sys, os
from pyklout import Klout
from simpleconfigparser import simpleconfigparser

config = simpleconfigparser()
config.read(os.environ['HOME'] +'/.twitter')

#don't overrun Klout API limit
time.sleep(.125)

api = Klout(config.Klout.key)

name = str(sys.argv[1])

data = api.identity(name,'twitter')
list = api.topics(data['id'])

for topic in list:
    disp =topic['displayName']
    slug =topic['slug']
    print name + "," + disp + "," + slug


