#!/usr/bin/env python
#DESC: print .twitter config file
import tweepy

#http://dev.twitter.com
#make an app, read only is fine
#CONSUMER_KEY = 'API consumer key'         
#CONSUMER_SECRET = 'API consumer secret'                               

auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth_url = auth.get_authorization_url()
print 'Please authorize: ' + auth_url
verifier = raw_input('PIN: ').strip()
auth.get_access_token(verifier)

print "[API]"
print "consumer_key = %s" % CONSUMER_KEY
print "consumer_secret = %s" % CONSUMER_SECRET
print "access_token_key = %s" % auth.access_token.key
print "access_token_secret = %s" % auth.access_token.secret

auth.set_access_token(auth.access_token.key, auth.access_token.secret)
api = tweepy.API(auth)
y = api.verify_credentials()
print "account = %s" % y.screen_name
print "homedir = Dropbox"
