#!/usr/bin/python
#DESC: print accounts a given screen name is following
import tweepy
import os
import sys
from simpleconfigparser import simpleconfigparser

config = simpleconfigparser()
config.read(os.environ['HOME'] +'/.twitter')


auth = tweepy.OAuthHandler(config.API.consumer_key, config.API.consumer_secret)
auth.set_access_token(config.API.access_token_key, config.API.access_token_secret)
api = tweepy.API(auth)

derps = api.friends_ids(sys.argv[1])
for derp in derps:
    name = api.get_user(derp).screen_name
    print name 
