#!/usr/bin/python
import urllib2,sys,tweepy,os
from simpleconfigparser import simpleconfigparser
from bs4 import BeautifulSoup

config = simpleconfigparser()
config.read(os.environ['HOME'] +'/.twitter')
print(config.API.homedir)
