#!/usr/bin/python
#DESC: Print lists for a given account
import tweepy
import csv
import sys
from simpleconfigparser import simpleconfigparser
import os
import re

config = simpleconfigparser()
config.read(os.environ['HOME'] +'/.twitter')


auth = tweepy.OAuthHandler(config.API.consumer_key, config.API.consumer_secret)
auth.set_access_token(config.API.access_token_key, config.API.access_token_secret)
api = tweepy.API(auth)

name = config.API.account
if len(sys.argv) > 1:
   name = sys.argv[1]

lists = api.lists_all(name)
for list in lists:
   print list.slug + "," + list.id_str
