#!/usr/bin/python
#DESC: print members of <USER'S> <LIST>
import tweepy
import csv
import sys
from simpleconfigparser import simpleconfigparser
import os

config = simpleconfigparser()
config.read(os.environ['HOME'] +'/.twitter')


auth = tweepy.OAuthHandler(config.API.consumer_key, config.API.consumer_secret)
auth.set_access_token(config.API.access_token_key, config.API.access_token_secret)
api = tweepy.API(auth)

for member in tweepy.Cursor(api.list_members, sys.argv[1], sys.argv[2]).items():
    print member.screen_name
