#!/usr/bin/python
#DESC: show name of account /w credentials in ~/.twitter 
import tweepy
import os
from simpleconfigparser import simpleconfigparser

config = simpleconfigparser()
config.read(os.environ['HOME'] +'/.twitter')


auth = tweepy.OAuthHandler(config.API.consumer_key, config.API.consumer_secret)
auth.set_access_token(config.API.access_token_key, config.API.access_token_secret)
api = tweepy.API(auth)


y = api.verify_credentials()
print y.screen_name
