#!/bin/bash
#DESC: new accounts to monitor get 'primed' with an empty file from 1970
cat $1 | awk -F "," {'print "echo 999999999999999999 > " $2 "-consolidated-1970-01-01-00-00.txt"'} > prime
sh prime
