#!/usr/bin/python
#DESC: given a tweet ID, couch up the full URL
#DESC: it's not clear if this is ever used, maybe
#DESC: for bulk screen shot duties??
import tweepy, csv, sys, os
from simpleconfigparser import simpleconfigparser

config = simpleconfigparser()
config.read(os.environ['HOME'] +'/.twitter')

auth = tweepy.OAuthHandler(config.API.consumer_key, config.API.consumer_secret)
auth.set_access_token(config.API.access_token_key, config.API.access_token_secret)
api = tweepy.API(auth)

name = config.API.account


tweet = api.get_status(sys.argv[1])
#print dir(tweet)
print tweet.source_url
