#!/usr/bin/python
#DESC: every other DM cleaner sucks. This sucks a little less. 
import tweepy, os
from simpleconfigparser import simpleconfigparser

config = simpleconfigparser()
config.read(os.environ['HOME'] +'/.twitter')

auth = tweepy.OAuthHandler(config.API.consumer_key, config.API.consumer_secret)
auth.set_access_token(config.API.access_token_key, config.API.access_token_secret)
api = tweepy.API(auth)

y = api.verify_credentials()
print y.screen_name

msgs = api.direct_messages()
for dm in msgs:
   print dm.id_str + " " + str(dm.created_at) + " " + dm.sender_screen_name  
   #+ " " + dm.text
   api.destroy_direct_message(dm.id)
