#!/usr/bin/python
#DESC: quickly nuke whatever tweets we can see
import tweepy, ps
from simpleconfigparser import simpleconfigparser

config = simpleconfigparser()
config.read(os.environ['HOME'] +'/.twitter')

auth = tweepy.OAuthHandler(config.API.consumer_key, config.API.consumer_secret)
auth.set_access_token(config.API.access_token_key, config.API.access_token_secret)
api = tweepy.API(auth)

y = api.verify_credentials()
print y.screen_name

tweets = api.user_timeline()
for tweet in tweets:
   print tweet.text.encode('utf-8')
   api.destroy_status(tweet.id)
